import { COLORS } from '../gameConfig';
import type { AssetRegistry } from './levelTypes';

export const BUILDING_IMPORTANCE = {
  'castle': 100,
  'market': 70,
  'house-1': 50,
  'house-2': 50,
};

export const ASSET_REGISTRY: AssetRegistry = {
  'grass': {
    token: 'grass',
    type: 'terrain',
    label: 'Grass',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldTilesAtlas',
      frameKey: 'grass_01',
      displaySize: [160, 160],
      origin: [0.5, 0.62],
      terrainFill: COLORS.grassA,
      terrainStroke: 0x5dbb65,
    },
  },
  'path': {
    token: 'path',
    type: 'path',
    label: 'Cobblestone Path',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldTilesAtlas',
      frameKey: 'stone_path_01',
      displaySize: [160, 160],
      origin: [0.5, 0.62],
      terrainFill: COLORS.path,
      terrainStroke: COLORS.pathEdge,
    },
  },
  'castle': {
    token: 'castle',
    type: 'building',
    label: 'Castle',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 3 },
    protected: true,
    importance: BUILDING_IMPORTANCE['castle'],
    maxHealth: 110,
    render: { textureKey: 'buildingsAtlas', frameKey: 'castle_01', displaySize: [316, 316], origin: [0.5, 0.84], alpha: 1, z: 18 },
  },
  'house-1': {
    token: 'house-1',
    type: 'building',
    label: 'Cottage',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE['house-1'],
    maxHealth: 74,
    render: { textureKey: 'buildingsAtlas', frameKey: 'house_orange_01', displaySize: [276, 276], origin: [0.5, 0.84], alpha: 1, z: 18 },
  },
  'house-2': {
    token: 'house-2',
    type: 'building',
    label: 'Bakery',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE['house-2'],
    maxHealth: 76,
    render: { textureKey: 'buildingsAtlas', frameKey: 'bakery_blue_01', displaySize: [276, 276], origin: [0.5, 0.84], alpha: 1, z: 18 },
  },
  'market': {
    token: 'market',
    type: 'building',
    label: 'Market',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE['market'],
    maxHealth: 68,
    render: { textureKey: 'buildingsAtlas', frameKey: 'market_01', displaySize: [276, 276], origin: [0.5, 0.86], alpha: 1, z: 18 },
  },
  'well': {
    token: 'well',
    type: 'prop',
    label: 'Well',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 2, h: 2 },
    render: { textureKey: 'buildingsAtlas', frameKey: 'well_01', displaySize: [276, 276], origin: [0.5, 0.82], alpha: 1, z: 7 },
  },
  'tree': {
    token: 'tree',
    type: 'prop',
    label: 'Forest Tree',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'pine_tree_01', displaySize: [204, 175], origin: [0.5, 0.84], alpha: 1, z: 12 },
  },
  'decoration': {
    token: 'decoration',
    type: 'terrain',
    label: 'Garden Decoration',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldTilesAtlas',
      frameKey: 'flower_bed_01',
      displaySize: [160, 160],
      origin: [0.5, 0.62],
      terrainFill: COLORS.garden,
      terrainStroke: 0xdf729f,
    },
  },
  'chest': {
    token: 'chest',
    type: 'interactable',
    label: 'Treasure Chest',
    walkable: true,
    blocksMovement: false,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'chest_closed_01', displaySize: [101, 103], origin: [0.5, 0.78], z: 10 },
  },
  'monster-spawn': {
    token: 'monster-spawn',
    type: 'spawn',
    label: 'Monster Spawn',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.forest, terrainStroke: 0x3e965e },
  },
  'village-center': {
    token: 'village-center',
    type: 'marker',
    label: 'Village Center',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.path, terrainStroke: COLORS.pathEdge },
  },
  'lamp': {
    token: 'lamp',
    type: 'prop',
    label: 'Lamp',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'lamp_01', displaySize: [162, 124], origin: [0.5, 0.86], alpha: 1, z: 7 },
  },
  'fence': {
    token: 'fence',
    type: 'prop',
    label: 'Fence',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'fence_01', displaySize: [156, 103], origin: [0.5, 0.82], alpha: 1, z: 6 },
  },
  'sign': {
    token: 'sign',
    type: 'prop',
    label: 'Sign',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'sign_01', displaySize: [144, 106], origin: [0.5, 0.86], alpha: 1, z: 7 },
  },
  'blocker': {
    token: 'blocker',
    type: 'blocker',
    label: 'Generic Blocker',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
  },
  'player-spawn': {
    token: 'player-spawn',
    type: 'marker',
    label: 'Player Spawn',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.path, terrainStroke: COLORS.pathEdge },
  },
};
