import { COLORS } from '../gameConfig';
import type { AssetRegistry } from './levelTypes';

export const BUILDING_IMPORTANCE = {
  C: 100,
  M: 70,
  H1: 50,
  H2: 50,
};

export const ASSET_REGISTRY: AssetRegistry = {
  G: {
    token: 'G',
    type: 'terrain',
    label: 'Grass',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldTilesAtlas',
      frameKey: 'grass_01',
      displaySize: [160, 160],
      origin: [0.5, 0.62],
      terrainFill: COLORS.grassA,
      terrainStroke: 0x5dbb65,
    },
  },
  P: {
    token: 'P',
    type: 'path',
    label: 'Cobblestone Path',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldTilesAtlas',
      frameKey: 'stone_path_01',
      displaySize: [160, 160],
      origin: [0.5, 0.62],
      terrainFill: COLORS.path,
      terrainStroke: COLORS.pathEdge,
    },
  },
  C: {
    token: 'C',
    type: 'building',
    label: 'Castle',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 3 },
    protected: true,
    importance: BUILDING_IMPORTANCE.C,
    maxHealth: 110,
    render: { textureKey: 'buildingsAtlas', frameKey: 'castle_01', displaySize: [299, 190], origin: [0.5, 0.84], alpha: 1, z: 18 },
  },
  H1: {
    token: 'H1',
    type: 'building',
    label: 'Cottage',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE.H1,
    maxHealth: 74,
    render: { textureKey: 'buildingsAtlas', frameKey: 'house_orange_01', displaySize: [237, 155], origin: [0.5, 0.84], alpha: 1, z: 18 },
  },
  H2: {
    token: 'H2',
    type: 'building',
    label: 'Bakery',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE.H2,
    maxHealth: 76,
    render: { textureKey: 'buildingsAtlas', frameKey: 'bakery_blue_01', displaySize: [235, 185], origin: [0.5, 0.84], alpha: 1, z: 18 },
  },
  M: {
    token: 'M',
    type: 'building',
    label: 'Market',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE.M,
    maxHealth: 68,
    render: { textureKey: 'buildingsAtlas', frameKey: 'market_01', displaySize: [220, 187], origin: [0.5, 0.86], alpha: 1, z: 18 },
  },
  W: {
    token: 'W',
    type: 'prop',
    label: 'Well',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 2, h: 2 },
    render: { textureKey: 'buildingsAtlas', frameKey: 'well_01', displaySize: [203, 157], origin: [0.5, 0.82], alpha: 1, z: 7 },
  },
  T: {
    token: 'T',
    type: 'prop',
    label: 'Forest Tree',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'pine_tree_01', displaySize: [204, 175], origin: [0.5, 0.84], alpha: 1, z: 12 },
  },
  D: {
    token: 'D',
    type: 'terrain',
    label: 'Garden Decoration',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldTilesAtlas',
      frameKey: 'flower_bed_01',
      displaySize: [160, 160],
      origin: [0.5, 0.62],
      terrainFill: COLORS.garden,
      terrainStroke: 0xdf729f,
    },
  },
  CH: {
    token: 'CH',
    type: 'interactable',
    label: 'Treasure Chest',
    walkable: true,
    blocksMovement: false,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'chest_closed_01', displaySize: [101, 103], origin: [0.5, 0.78], z: 10 },
  },
  SP: {
    token: 'SP',
    type: 'spawn',
    label: 'Monster Spawn',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.forest, terrainStroke: 0x3e965e },
  },
  V: {
    token: 'V',
    type: 'marker',
    label: 'Village Center',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.path, terrainStroke: COLORS.pathEdge },
  },
  L: {
    token: 'L',
    type: 'prop',
    label: 'Lamp',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'lamp_01', displaySize: [162, 124], origin: [0.5, 0.86], alpha: 1, z: 7 },
  },
  F: {
    token: 'F',
    type: 'prop',
    label: 'Fence',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'fence_01', displaySize: [156, 103], origin: [0.5, 0.82], alpha: 1, z: 6 },
  },
  S: {
    token: 'S',
    type: 'prop',
    label: 'Sign',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldTilesAtlas', frameKey: 'sign_01', displaySize: [144, 106], origin: [0.5, 0.86], alpha: 1, z: 7 },
  },
  B: {
    token: 'B',
    type: 'blocker',
    label: 'Generic Blocker',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
  },
  PS: {
    token: 'PS',
    type: 'marker',
    label: 'Player Spawn',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.path, terrainStroke: COLORS.pathEdge },
  },
};
