import { COLORS } from '../gameConfig';
import type { AssetRegistry } from './levelTypes';

export const BUILDING_IMPORTANCE = {
  C: 100,
  M: 70,
  H1: 50,
  H2: 50,
};

export const ASSET_REGISTRY: AssetRegistry = {
  G: {
    token: 'G',
    type: 'terrain',
    label: 'Grass',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldSheet',
      frameKey: 'world-grass-tile',
      displaySize: [104, 82],
      origin: [0.5, 0.62],
      terrainFill: COLORS.grassA,
      terrainStroke: 0x5dbb65,
    },
    needsSlicing: true,
  },
  P: {
    token: 'P',
    type: 'path',
    label: 'Cobblestone Path',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldSheet',
      frameKey: 'world-path-tile',
      displaySize: [104, 82],
      origin: [0.5, 0.62],
      terrainFill: COLORS.path,
      terrainStroke: COLORS.pathEdge,
    },
    needsSlicing: true,
  },
  C: {
    token: 'C',
    type: 'building',
    label: 'Castle',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 3 },
    protected: true,
    importance: BUILDING_IMPORTANCE.C,
    maxHealth: 110,
    render: { textureKey: 'worldSheet', frameKey: 'world-castle', displaySize: [178, 160], origin: [0.5, 0.84], alpha: 0.94, z: 18 },
    needsSlicing: true,
  },
  H1: {
    token: 'H1',
    type: 'building',
    label: 'Cottage',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE.H1,
    maxHealth: 74,
    render: { textureKey: 'worldSheet', frameKey: 'world-house-orange', displaySize: [138, 120], origin: [0.5, 0.84], alpha: 0.94, z: 18 },
    needsSlicing: true,
  },
  H2: {
    token: 'H2',
    type: 'building',
    label: 'Bakery',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE.H2,
    maxHealth: 76,
    render: { textureKey: 'worldSheet', frameKey: 'world-bakery-blue', displaySize: [146, 124], origin: [0.5, 0.84], alpha: 0.94, z: 18 },
    needsSlicing: true,
  },
  M: {
    token: 'M',
    type: 'building',
    label: 'Market',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 3, h: 2 },
    protected: true,
    importance: BUILDING_IMPORTANCE.M,
    maxHealth: 68,
    render: { textureKey: 'worldSheet', frameKey: 'world-market', displaySize: [140, 122], origin: [0.5, 0.86], alpha: 0.94, z: 18 },
    needsSlicing: true,
  },
  W: {
    token: 'W',
    type: 'prop',
    label: 'Well',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 2, h: 2 },
    render: { textureKey: 'worldSheet', frameKey: 'world-well', displaySize: [86, 96], origin: [0.5, 0.82], alpha: 0.92, z: 7 },
    needsSlicing: true,
  },
  T: {
    token: 'T',
    type: 'prop',
    label: 'Forest Tree',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldSheet', frameKey: 'world-pine', displaySize: [72, 110], origin: [0.5, 0.84], alpha: 0.9, z: 12 },
    needsSlicing: true,
  },
  D: {
    token: 'D',
    type: 'terrain',
    label: 'Garden Decoration',
    walkable: true,
    blocksMovement: false,
    render: {
      textureKey: 'worldSheet',
      frameKey: 'world-garden-tile',
      displaySize: [104, 82],
      origin: [0.5, 0.62],
      terrainFill: COLORS.garden,
      terrainStroke: 0xdf729f,
    },
    needsSlicing: true,
  },
  CH: {
    token: 'CH',
    type: 'interactable',
    label: 'Treasure Chest',
    walkable: true,
    blocksMovement: false,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'chestTexture', displaySize: [58, 58], origin: [0.5, 0.78], z: 10 },
    needsSlicing: true,
  },
  SP: {
    token: 'SP',
    type: 'spawn',
    label: 'Monster Spawn',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.forest, terrainStroke: 0x3e965e },
  },
  V: {
    token: 'V',
    type: 'marker',
    label: 'Village Center',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.path, terrainStroke: COLORS.pathEdge },
  },
  L: {
    token: 'L',
    type: 'prop',
    label: 'Lamp',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldSheet', frameKey: 'world-lamp', displaySize: [36, 86], origin: [0.5, 0.86], alpha: 0.9, z: 7 },
    needsSlicing: true,
  },
  F: {
    token: 'F',
    type: 'prop',
    label: 'Fence',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldSheet', frameKey: 'world-fence', displaySize: [82, 58], origin: [0.5, 0.82], alpha: 0.88, z: 6 },
    needsSlicing: true,
  },
  S: {
    token: 'S',
    type: 'prop',
    label: 'Sign',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
    render: { textureKey: 'worldSheet', frameKey: 'world-sign', displaySize: [72, 82], origin: [0.5, 0.86], alpha: 0.9, z: 7 },
    needsSlicing: true,
  },
  B: {
    token: 'B',
    type: 'blocker',
    label: 'Generic Blocker',
    walkable: false,
    blocksMovement: true,
    footprint: { w: 1, h: 1 },
  },
  PS: {
    token: 'PS',
    type: 'marker',
    label: 'Player Spawn',
    walkable: true,
    blocksMovement: false,
    render: { terrainFill: COLORS.path, terrainStroke: COLORS.pathEdge },
  },
};
