import type { LevelConfig } from './levelTypes';

export const DEFAULT_VILLAGE_LEVEL: LevelConfig = {
  seed: 'village-001',
  timeOfDay: 'morning',
  tileSize: 54,
  decorationDensity: 0.48,
  difficulty: 1,
  matrix: [
    ['T', 'T', 'T', 'T', 'SP', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'SP', 'T', 'T', 'T', 'T'],
    ['T', 'T', 'G', 'G', 'P', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'P', 'G', 'G', 'T', 'T'],
    ['T', 'G', 'D', 'G', 'P', 'P', 'P', 'P', 'G', 'G', 'G', 'P', 'P', 'P', 'P', 'G', 'D', 'G', 'T'],
    ['T', 'G', 'G', 'G', 'P', 'P', 'G', 'P', 'P', 'P', 'P', 'P', 'G', 'P', 'P', 'G', 'G', 'G', 'T'],
    ['SP', 'P', 'P', 'P', 'P', 'P', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'P', 'P', 'P', 'P', 'P', 'SP'],
    ['T', 'G', 'G', 'G', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'G', 'G', 'G', 'T'],
    ['T', 'G', 'D', 'G', 'P', 'P', 'P', 'G', 'P', 'P', 'P', 'P', 'G', 'P', 'P', 'P', 'D', 'G', 'T'],
    ['T', 'G', 'G', 'G', 'P', 'G', 'P', 'P', 'P', 'G', 'PS', 'G', 'P', 'P', 'P', 'G', 'G', 'G', 'T'],
    ['T', 'G', 'G', 'P', 'P', 'G', 'G', 'G', 'P', 'P', 'P', 'P', 'P', 'G', 'G', 'P', 'P', 'G', 'T'],
    ['T', 'G', 'G', 'P', 'G', 'G', 'G', 'G', 'P', 'V', 'C', 'V', 'P', 'G', 'G', 'G', 'P', 'G', 'T'],
    ['T', 'G', 'D', 'P', 'G', 'G', 'G', 'G', 'P', 'V', 'V', 'G', 'P', 'G', 'G', 'G', 'P', 'D', 'T'],
    ['T', 'G', 'G', 'P', 'P', 'P', 'P', 'H1', 'P', 'P', 'P', 'P', 'P', 'G', 'P', 'P', 'P', 'G', 'T'],
    ['T', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'P', 'P', 'P', 'P', 'P', 'H2', 'G', 'G', 'G', 'G', 'T'],
    ['T', 'G', 'D', 'G', 'P', 'P', 'P', 'P', 'P', 'G', 'M', 'G', 'P', 'P', 'P', 'G', 'D', 'G', 'T'],
    ['T', 'G', 'CH', 'G', 'P', 'G', 'D', 'G', 'P', 'G', 'G', 'G', 'P', 'G', 'P', 'G', 'CH', 'G', 'T'],
    ['T', 'G', 'G', 'G', 'P', 'P', 'P', 'G', 'P', 'P', 'P', 'G', 'P', 'P', 'P', 'G', 'G', 'G', 'T'],
    ['T', 'G', 'CH', 'G', 'P', 'G', 'P', 'G', 'G', 'G', 'G', 'G', 'P', 'G', 'P', 'G', 'CH', 'G', 'T'],
    ['T', 'T', 'G', 'G', 'P', 'G', 'P', 'G', 'G', 'G', 'G', 'G', 'P', 'G', 'P', 'G', 'G', 'T', 'T'],
    ['T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T'],
  ],
};
