export interface SceneAPI {
  add: any;
  input: any;
  tweens: any;
  textures: any;
  time: any;
  make: any;
  events: any;
  scale: any;
  game: any;
  sys: any;
  scene: any;
  load: any;
  anims: any;
  renderer: any;

  state: any;
  heroClass: any;
  audio: any;
  player: any;
  enemies: any[];
  buildings: any[];
  playerOccluders: any[];
  projectiles: any[];
  traps: any[];
  guardUntil: number;
  runStats: any;
  heartDropDefeatStreak: number;
  effects: any[];
  notes: any[];
  keys: Record<string, any>;
  parallaxSprites: any[];
  touchControls: any;
  touchControlsEnabled: boolean;
  touchDetection: any;
  touchLayer: any;
  controlsHint: any;
  lastTouchControlsVisibility: boolean | null;
  generatedLevel: any;
  generatedLevelActive: boolean;
  generatedTerrainMask: any;
  generatedTerrainMaskGraphics: any;
  levelDebugLayer: any;
  levelDebugGraphics: any;
  levelDebugVisible: boolean;
  levelDebugLastRenderAt: number;
  tileGraphics: any;
  lightingLayer: any;
  backgroundLayer: any;
  edgeLayer: any;
  shadowLayer: any;
  waterLayer: any;
  decorLayer: any;
  buildingLayer: any;
  characterLayer: any;
  effectsLayer: any;
  hudLayer: any;
  uiLayer: any;
  fxLayer: any;
  entityLayer: any;
  worldLayer: any;
  terrainBaseLayer: any;
  sceneVariant: any;

  ensureAudio(): void;
  uiTextStyle(size: number, color: string): any;
  addGuildNote(message: string): void;
  updateHud?(): void;
  playTone(type?: string): void;
  isoToScreen(x: number, y: number, z?: number): { x: number; y: number };
  scaleGeneratedSize(size: [number, number]): [number, number];
  getIsoMetrics(): { tileW: number; tileH: number };
  clampIso(point: { x: number; y: number }, padding?: number): { x: number; y: number };
  screenToIso(x: number, y: number): { x: number; y: number };
  isGeneratedIsoWalkable(iso: { x: number; y: number }): boolean;
  getFootprintScreenBounds(cells: Array<{ x: number; y: number }>): any;
  getGeneratedFootprintSpriteLayout(placement: any, render: any, fallbackFrameSize: [number, number]): any;
  getFootprintCells(x: number, y: number, footprint?: { w: number; h: number }): Array<{ x: number; y: number }>;
  createBuildingHealthBar(x: number, y: number, width: number, height: number, depth: number): any;
  updateBuildingHealthBar(building: any): void;
  getSceneVariantBuildingTexture(placement: any): any;
  getSceneVariantPropTexture(placement: any): any;
  getSceneVariantDecorationTexture(placement: any): any;
  isGeneratedBoardEdgeCell(grid: { x: number; y: number }): boolean;
  addEnvironmentUniformSprite(layer: any, frame: string, x: number, y: number, uniformScale: number, depth: number, options?: any): any;
  getActiveSceneVariant(): any;
  getGeneratedWorldBounds(tileW: number, tileH: number): any;
  registerPlayerOccluder(occluder: any): void;

  damageEnemy(target: any, power: number, type: string): void;

  // Combat / repair methods called from touch controls
  useMainAttack(time: number, targetIso: { x: number; y: number }): void;
  useClassSkill(time: number): void;
  tryRepairBuilding(): void;
  getAutoTargetIso(maxRange: number): { x: number; y: number };
  getHeroConfig(): any;
  getSkillConfig(): any;
  getNearestDamagedBuilding(): any;
  setMagicShield(shield: any): void;
  updateMagicShield(time: number): void;
  damageProtectedBuilding(building: any, amount: number): void;
  showLevelUpScreen(): void;
  checkLevelClear(): void;
  spawnSparkleBurst(x: number, y: number, color: number, count: number, scale: number): void;
  spawnShieldGlow(): void;
  spawnRoundEnemy(level: number, role: any): boolean;
  getEnemyFrameKey(enemy: any, frame: number): string;
  getCurrentWorldTheme(): any;

  playerStats: any;
  levelTimers: any[];
  levelUpOverlay: any;
  countdownOverlay?: any;
  countdownLevelText: any;
  countdownNumberText: any;

  // Combat state
  roundEnemyQueue: any[];
  levelSpawnsPending: number;
  levelDefeatsThisRound: number;
  levelEnemiesRemaining: number;
  levelRequiredDefeats: number;
  levelSpawnFailures: number;
  levelSpawnedCount: number;
}
